# Generated by Django 5.0 on 2023-12-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
