# Generated by Django 5.0 on 2024-02-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_end_date_alter_event_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created',
        ),
    ]
