# Generated by Django 5.0 on 2023-12-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_date_alter_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(),
        ),
    ]
