# Generated by Django 5.0 on 2024-02-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_image_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interested',
            name='created',
        ),
        migrations.RemoveField(
            model_name='interested',
            name='is_interested',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
