# Generated by Django 5.0 on 2024-02-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_category_id_alter_event_id_alter_rating_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interested',
            name='event',
        ),
        migrations.AddField(
            model_name='interested',
            name='event',
            field=models.ManyToManyField(to='events.event'),
        ),
    ]
