# Generated by Django 5.0 on 2024-03-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_category_created_remove_tag_created'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organiser')),
            ],
        ),
    ]
