# Generated by Django 5.0 on 2024-02-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventapproval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventApproval',
        ),
    ]
