# Generated by Django 5.0 on 2023-12-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_events_date_alter_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
