# Generated by Django 5.0 on 2023-12-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_events_end_date_remove_events_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='time',
            new_name='start_time',
        ),
    ]
