# Generated by Django 5.0 on 2023-12-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_date_events_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start_time',
            new_name='time',
        ),
    ]
