# Generated by Django 5.0 on 2023-12-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_rename_start_date_events_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
