# Generated by Django 5.0 on 2023-12-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_events_date_remove_events_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='source_link',
        ),
        migrations.RemoveField(
            model_name='events',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='events',
            name='vote_total',
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='tags',
            field=models.ManyToManyField(null=True, to='events.tag'),
        ),
    ]
