# Generated by Django 5.0 on 2024-02-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='selectedticket',
            constraint=models.UniqueConstraint(fields=('cart', 'ticket'), name='ticket_in_cart'),
        ),
    ]
