# Generated by Django 2.2.28 on 2024-02-01 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedticket',
            name='issued_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Attendee'),
        ),
        migrations.AddField(
            model_name='selectedticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketType'),
        ),
    ]
