# Generated by Django 5.0 on 2023-12-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_selectedticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettype',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selectedticket',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('CONFIRMED', 'Confirmed')], default='AVAILABLE', max_length=255),
        ),
    ]
