# Generated by Django 5.0 on 2024-02-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
